FROM python:3.9.13-alpine

RUN apk add --update --no-cache bash py3-pip && rm -rf /tmp/* /var/cache/apk/*

COPY bin/init_oid_filename_mapping.sh /bin
RUN chmod +x /bin/init_oid_filename_mapping.sh

WORKDIR /code
