version: "3.9"

services:
  vulnerability-tests:
    image: ghcr.io/greenbone/vulnerability-tests:enterprise-main
    container_name: recording_vts
    environment:
      STORAGE_PATH: /var/lib/openvas/21.04/vt-data/nasl
    volumes:
      - vt_data_vol:/mnt

  redis-server:
    image: greenbone/redis-server
    container_name: recording_redis_server
    restart: on-failure
    #cap_drop:
    #  - ALL
    #ports:
    #  - 6379:6379
    volumes:
      - /tmp/gvm/redis_socket:/run/redis/

  openvas-scanner:
    build:
      context: .
      dockerfile: Dockerfile_OpenVAS
    cap_add:
      - NET_ADMIN
    command: bash /bin/init_scanner_container.sh
    container_name: recording_openvas_scanner
    network_mode: "bridge"
    volumes:
      - vt_data_vol:/var/lib/openvas/plugins
      - /tmp/gvm/redis_socket:/run/redis/
    networks:
      inside_scanner_to_proxy_net:
        ipv4_address: 10.5.0.6
    depends_on:
      - vulnerability-tests
      - redis-server

  recorder-router:
    build:
      context: .
      dockerfile: Dockerfile_Recorder
    command: bash /bin/init_recorder_container.sh
    container_name: recording_recorder
    network_mode: "bridge"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ../:/code
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      inside_scanner_to_proxy_net:
        ipv4_address: 10.5.0.5
    depends_on:
      - openvas-scanner

volumes:
  vt_data_vol:

networks:
  inside_scanner_to_proxy_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
